; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = myboards

[env:JC8048W550C]
platform = espressif32
framework = arduino
board = JC8048W550C
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
build_flags = 
	-D BOARD_NAME="JC8048W550C"
	-D BOARD_HAS_PSRAM
	-Ofast
	-Wall
	'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO'
	-D LV_CONF_PATH=${PROJECT_INCLUDE_DIR}/lv_conf.h
	-D LV_CONF_INCLUDE_SIMPLE
	-I include
	-D LV_CONF_INCLUDE_SIMPLE
	-D DISABLE_BROWNOUT
    -D ESP_LCD_TOUCH_I2C_GT911_ADDRESS=0x5D
lib_deps = 
	rzeldent/esp32_smartdisplay
	lvgl/lvgl@9.2.0